import { resolve } from 'node:path';
import fs from 'fs-extra';

interface ServiceDef {
  image: string;
  ports: string[];
  environment?: Record<string, string>;
  volumes?: string[];
  healthcheck?: {
    test: string;
    interval: string;
    timeout: string;
    retries: number;
  };
}

const SERVICE_DEFS: Record<string, ServiceDef> = {
  postgres: {
    image: 'postgres:16-alpine',
    ports: ['5432:5432'],
    environment: {
      POSTGRES_USER: '${DB_USER:-admin}',
      POSTGRES_PASSWORD: '${DB_PASSWORD:-admin}',
      POSTGRES_DB: '${DB_NAME:-app_dev}',
    },
    volumes: ['pgdata:/var/lib/postgresql/data'],
    healthcheck: {
      test: 'pg_isready -U $$POSTGRES_USER',
      interval: '5s',
      timeout: '3s',
      retries: 5,
    },
  },
  redis: {
    image: 'redis:7-alpine',
    ports: ['6379:6379'],
    healthcheck: {
      test: 'redis-cli ping',
      interval: '5s',
      timeout: '3s',
      retries: 5,
    },
  },
  rabbitmq: {
    image: 'rabbitmq:3-management-alpine',
    ports: ['5672:5672', '15672:15672'],
    environment: {
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USER:-admin}',
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASS:-admin}',
    },
    healthcheck: {
      test: 'rabbitmq-diagnostics -q ping',
      interval: '10s',
      timeout: '5s',
      retries: 5,
    },
  },
  minio: {
    image: 'minio/minio:latest',
    ports: ['9000:9000', '9001:9001'],
    environment: {
      MINIO_ROOT_USER: '${MINIO_USER:-admin}',
      MINIO_ROOT_PASSWORD: '${MINIO_PASSWORD:-admin123}',
    },
    volumes: ['minio_data:/data'],
  },
};

/**
 * Genera un docker-compose.yml con los servicios seleccionados
 */
export async function generateDockerCompose(
  root: string,
  services: string[],
): Promise<void> {
  const compose: Record<string, unknown> = {
    services: {} as Record<string, unknown>,
    volumes: {} as Record<string, unknown>,
  };

  const volumes: Record<string, unknown> = {};

  for (const svc of services) {
    const def = SERVICE_DEFS[svc];
    if (!def) continue;

    const svcConfig: Record<string, unknown> = {
      image: def.image,
      ports: def.ports,
      restart: 'unless-stopped',
    };

    if (def.environment) svcConfig['environment'] = def.environment;
    if (def.healthcheck) svcConfig['healthcheck'] = def.healthcheck;
    if (def.volumes) {
      svcConfig['volumes'] = def.volumes;
      for (const vol of def.volumes) {
        const volName = vol.split(':')[0];
        volumes[volName] = {};
      }
    }

    (compose['services'] as Record<string, unknown>)[svc] = svcConfig;
  }

  if (Object.keys(volumes).length > 0) {
    compose['volumes'] = volumes;
  }

  // Escribir como YAML manualmente (evitamos dependencia de js-yaml)
  const yaml = toYaml(compose);
  await fs.writeFile(resolve(root, 'docker-compose.yml'), yaml, 'utf-8');

  // .env.example
  const envExample = generateEnvExample(services);
  await fs.writeFile(resolve(root, '.env.example'), envExample, 'utf-8');
}

function toYaml(obj: unknown, indent = 0): string {
  const pad = ' '.repeat(indent);

  if (obj === null || obj === undefined) return 'null';
  if (typeof obj === 'string') return obj.includes('$') ? `"${obj}"` : obj;
  if (typeof obj === 'number' || typeof obj === 'boolean') return String(obj);

  if (Array.isArray(obj)) {
    return obj
      .map((item) => `${pad}- ${toYaml(item, indent + 2).trim()}`)
      .join('\n');
  }

  if (typeof obj === 'object') {
    const entries = Object.entries(obj as Record<string, unknown>);
    if (entries.length === 0) return '';

    return entries
      .map(([key, val]) => {
        if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
          const nested = toYaml(val, indent + 2);
          if (!nested) return `${pad}${key}:`;
          return `${pad}${key}:\n${nested}`;
        }
        if (Array.isArray(val)) {
          const items = toYaml(val, indent + 2);
          return `${pad}${key}:\n${items}`;
        }
        return `${pad}${key}: ${toYaml(val, indent)}`;
      })
      .join('\n');
  }

  return String(obj);
}

function generateEnvExample(services: string[]): string {
  const lines = ['# Generated by @e-burgos/sdd-harness', ''];

  if (services.includes('postgres')) {
    lines.push('# PostgreSQL');
    lines.push('DB_USER=admin');
    lines.push('DB_PASSWORD=admin');
    lines.push('DB_NAME=app_dev');
    lines.push('DATABASE_URL=postgresql://admin:admin@localhost:5432/app_dev');
    lines.push('');
  }

  if (services.includes('redis')) {
    lines.push('# Redis');
    lines.push('REDIS_URL=redis://localhost:6379');
    lines.push('');
  }

  if (services.includes('rabbitmq')) {
    lines.push('# RabbitMQ');
    lines.push('RABBITMQ_USER=admin');
    lines.push('RABBITMQ_PASS=admin');
    lines.push('RABBITMQ_URL=amqp://admin:admin@localhost:5672');
    lines.push('');
  }

  if (services.includes('minio')) {
    lines.push('# MinIO (S3-compatible)');
    lines.push('MINIO_USER=admin');
    lines.push('MINIO_PASSWORD=admin123');
    lines.push('MINIO_ENDPOINT=http://localhost:9000');
    lines.push('');
  }

  lines.push('# App');
  lines.push('NODE_ENV=development');
  lines.push('JWT_SECRET=change-me-in-production');
  lines.push('');

  return lines.join('\n');
}
